### ISSUE TITLE
Typo in Build from source section

### ISSUE THREAD

**Issue by ferrantim** [ClusterHQ/fli#11]
https://github.com/ClusterHQ/fli#build-fli-from-source

Fli can also be built from source. Instruction to build from source can be found here.

Should be 

Fli can also be built from source. Instructions to build from source can be found here.

**Comment by pankajku** [comment]
The build instructions work only on Linux machine, not all platforms supported by Go. Perhaps worth pointing out at https://fli-docs.clusterhq.com/en/latest/Contributing.html#how-to-build-from-source
