### ISSUE TITLE
"Invalid VHUT format" during fli config

### ISSUE THREAD

**Issue by albertnguyen3shape** [ClusterHQ/fli#3]
I have created an account on flockerhub and created a token. 

Then I followed the guide and configured fli to use the token:

`fli config --token $HOME/token.txt`

Problem is I get the following response from fli:

**Invalid VHUT format**

**Comment by DasAng** [comment]
I've a similar issue. So I went and looked at the fli source code:

````
func (v *VHUT) validFormat() bool {
	comps := strings.Split(v.vhut, "|")
	if len(comps) != 5 || comps[0] != "V1" {
		return false
	}
	return true
}

// InitFromFile initializes member vhut from contents of the file.
// This will most likley be invoked by a CLI program that stores the VHUT in a file
// Returns non-nil error if the file doesn't exist, can't be read or the data doesn't
// match the VHUT format. It is to be noted that this method doesn't validate the token
func (v *VHUT) InitFromFile(filename string) error {
	bytes, err := ioutil.ReadFile(filename)
	if err != nil {
		return err
	}

	return v.InitFromString(strings.TrimSpace(string(bytes)))
}
````

I've pinpointed the problem. It seems that the token file that gets created somehow has a UTF8 BOM Marker at the beginning of the file which trips over the comparison against "V1".
So for example if your token file looked something like this:

**"V1|U|xxx|sometoken|xxx"**

Then the hex codes will look somethin like this:

**efbbbf5631 55 787878 736f6d65746f6b656e 787878**

Notice the BOM marker **efbbbf** at the beginning. So when doing a comparison against "V1" it will fail du to the BOM marker.

A solution could be to modify the code to handle BOM marker appropriately.

Right now I had to re-save the file again as ANSI instead or manually remove the BOM Marker from the file to make it work.

**Comment by wallnerryan** [comment]
Thanks for bringing up this Issue @albertnguyen3shape @DasAng ! We did his is previously and are aware of the issue, thanks for your PR!

**Comment by wallnerryan** [comment]
@DasAng @albertnguyen3shape were you both able to get around the issue in the meantime while its being fixed to try `fli` ?

**Comment by DasAng** [comment]
@wallnerryan I've managed to get around it by manually removing the BOM Marker from the file or saving is as ANSI instead.

**Comment by wallnerryan** [comment]
Great, @DasAng let us know if you have any other issues, appreciate it.

**Comment by ferrantim** [comment]
this is fixed now. Details here: https://github.com/ClusterHQ/fli/pull/4  Thanks for reporting the issue!
